name: user_profile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  get_it: ^7.2.0
  injectable: ^1.5.3
  dio: ^4.0.4
  retrofit: ^3.0.1+1
  flutter_bloc: ^8.0.1
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  shared_preferences: ^2.0.13


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  injectable_generator: ^1.5.3
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  retrofit_generator: ^4.0.0
  freezed: ^1.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
